### PR TITLE
Fix for complex-formatted Telegram text

### PR DESCRIPTION
**Pull request by ValdikSS**
This patchset fixes issue #909.
> Long messages (posts forwarded to bridged chat from telegram channel) with multiple URLs gets corrupted: the URLs are misplaced and appear in the middle of the text, rewriting original text in this place.

### CODE REVIEW

**Comment by ValdikSS** [comment]
Tested with Latin, Russian and Chinese, so I guess no need to explicitly encode as utf16.

**Comment by ValdikSS** [comment]
Turned out that Unicode emojis break the markup, fixed by processing everything in utf16.

**Comment by 42wim** [comment]
@ValdikSS thanks a lot for looking into this!
could you just run a `gofmt -s` on handlers.go so the linter is happy and I can merge it

**Comment by ValdikSS** [comment]
> @ValdikSS thanks a lot for looking into this! could you just run a `gofmt -s` on handlers.go so the linter is happy and I can merge it

Done, please check.

**Comment by 42wim** [comment]
Thanks!

**Pull request merged**
