### PR TITLE
allow to send files in Extra via /api/message

### PR DESCRIPTION
**Pull request by adbenitez**
feel free to take over the PR if something is wrong or to tweak, I am a golang noob

### CODE REVIEW

**Comment by 42wim** [comment]
LGTM, thanks!

**Comment by tehsu** [comment]
can this be used to send images?

**Comment by adbenitez** [comment]
any file you want

**Comment by LawrenceWence** [comment]
@adbenitez any chance that you would provide a working example? I can't figure our how to properly submit a png/jpeg via extra data

**Comment by UnkwUsr** [comment]
@LawrenceWence you have to send next json to api endpoint just as you sending text:
```json
"Extra" : {
    "file": [
        {
            "Data": "here should be base64 encoded file",
            "Name": "filename"
            "Comment": "comment, just text"
        }
    ]
}
```
But there is also problem that current latest release version (`1.26.0`) is broken (at least for me, with forwarding to telegram), so you might need to build manually master branch version of matterbridge. https://github.com/42wim/matterbridge/issues/2182

**Pull request merged**
