### PR TITLE
Handle Whatsapp threading/replies

### PR DESCRIPTION
**Pull request by yousefmansy1**
Handle Whatsapp threading/replies, based on commit 6afa93e537c53b371db37f35a3546ff0fb669416 from #1934
In this change we are updating whatsapp message IDs to include sender JID as this is necessary to reply to a message 
- https://github.com/tulir/whatsmeow/issues/88#issuecomment-1093195237 
- https://github.com/tulir/whatsmeow/discussions/148#discussioncomment-3094325

image

### CODE REVIEW

**Comment by yousefmansy1** [comment]
@ilmaisin, have you tried sending messages back to WhatsApp?
I couldn't figure out how to get it to work. 
Based on your contribution history it looks like you know more than I do with the whatsmeow API.

**Comment by yousefmansy1** [comment]
Finally figured out the issue.
I was 90% of the way there, you actually also need to add a `QuotedMessage` to the context info.

Only figured it out by taking a look at the mautrix-whatsapp repo and tracing through what they're doing.
https://github.com/mautrix/whatsapp/blob/e0a9b0e8bb25b70196b78079dca2eeef35d526b6/portal.go#L3719-L3726

**Comment by yousefmansy1** [comment]
Replies should work across the board now.
@qaisjp do you think you can take a look?

Or perhaps @ilmaisin since you've made some commits to the whatsappmulti bridge.

(will post screenshots later its late I'm tired lol)

**Comment by ilmaisin** [comment]
> Replies should work across the board now. @qaisjp do you think you can take a look?
> 
> Or perhaps @ilmaisin since you've made some commits to the whatsappmulti bridge.
> 
> (will post screenshots later its late I'm tired lol)

Should your PR now work in both directions? I can probaly try it this weekend. I have my draft PR running in my instance, but it is rx-only.

**Comment by yousefmansy1** [comment]
> 
> Should your PR now work in both directions? I can probaly try it this weekend. I have my draft PR running in my instance, but it is rx-only. 

Yes it works in both directions. 👍

**Comment by ilmaisin** [comment]
If a Telegram user replies to a message orignating in Whatsapp, the reply that is sent back to Whatsapp includes both the "proper" quote as well as a textual quote. This may be a matter of another PR, though.
matterbridge-wa-quote

**Comment by yousefmansy1** [comment]
> If a Telegram user replies to a message orignating in Whatsapp, the reply that is sent back to Whatsapp includes both the "proper" quote as well as a textual quote. This may be a matter of another PR, though. matterbridge-wa-quote

I believe this might be unavoidable, as then you have `QuoteDisable=false` it will append reply information directly into the message text. 
The receiving bridges will simply relay whatever is in the message.Text body.
https://github.com/42wim/matterbridge/blob/24f6747516a9a80f82068656df50b3972928ba56/bridge/telegram/handlers.go#L113-L119

This would require some more significant rework of how replies work to resolve.

For now you'll just have to use `QuoteDisable=true`

**Comment by 42wim** [comment]
Great job @yousefmansy1 !

**Pull request merged**
