### PR TITLE
Add support for receiving attachments (keybase)

### PR DESCRIPTION
**Pull request by goncalor**
These changes make the Keybase bridge able to receive attachments.
It seems the Keybase API does not currently support uploading files directly from RAM, so the file has to be temporarily written to the filesystem before uploading and is removed afterwards.

I tested these changes by sending attachments from Telegram to Keybase.
This is my first time both contributing to this project and writing Go. Improvements/suggestions are appreciated.

### CODE REVIEW

**Comment by qaisjp** [comment]
Have you considered sending a pull request to the Keybase bridge to add support for loading from memory?

**Comment by goncalor** [comment]
@qaisjp if you mean the library `github.com/keybase/go-keybase-chat-bot/kbchat`, yes I thought about it and looked at the code a bit. But I don't think the keybase client itself supports this at the moment, so the library above couldn't provide it. I tried to mess around with `keybase chap api` and for uploads the filename seems to be mandatory (but I haven't found any great documentation for the API).

**Comment by qaisjp** [comment]
Fair enough. Btw, your code only looks like it supports one attachment? 

[This search](https://github.com/42wim/matterbridge/search?q=Extra%5B%22file%22%5D&unscoped_q=Extra%5B%22file%22%5D) suggests you should be doing a for loop through `msg.Extra["file"]`

**Comment by 42wim** [comment]
Hi @goncalor thanks for your PR!
I agree with @qaisjp regarding the looping over the uploads, could you add this change? 
Then I can merge your PR

**Comment by goncalor** [comment]
Hi @42wim. You're welcome. I agree with both you and @qaisjp, it should definitely loop through attachments.

I just have one question related to how `matterbridge` works and that was in part with I didn't add the looping from the start: it is ok to loop through the files and call `SendAttachmentByTeam()` for each of them (which should create more than one message on Keybase) but then return a single `resp.Result.MsgID`?

**Comment by 42wim** [comment]
For uploads of files we ignore the msgID because we can only return 1 msgID at the moment.
So it's fine to just return `"",nil` when finished

**Comment by goncalor** [comment]
Should be OK to merge now. Please check if any further changes are needed. Thank you.

**Comment by 42wim** [comment]
looks good, thank you 👍

**Pull request merged**
