### PR TITLE
Update of nlopes/slack dependency

### PR DESCRIPTION
**Pull request by Helcaraxan**
Result of running:
> vgo get -u github.com/nlopes/slack
> vgo mod tidy
> vgo mod vendor

Prerequisite for work on #510

### CODE REVIEW

**Comment by 42wim** [comment]
The strange thing here is why it vendors changes in 
```
vendor/github.com/labstack/echo
vendor/github.com/pelletier/go-toml
```
I did the same as you but using `go` instead of `vgo` but the labstack or go-toml didn't get added.

**Comment by Helcaraxan** [comment]
@42wim interesting. I just ran the same with:
```
 -> GO111MODULE=on go get -u github.com/nlopes/slack
 -> GO111MODULE=on go mod tidy
 -> GO111MODULE=on go mod vendor
```
and it does add those for me.

Does this bother you? I can remove them but that risks making things inconsistent.

**Comment by 42wim** [comment]
Hm, ok I found the issue, I have *.toml in my .gitignore :/

**Comment by 42wim** [comment]
Thanks!

**Pull request merged**
