### PR TITLE
Add support for Harmony

### PR DESCRIPTION
**Pull request by pontaoski**
Harmony is a relatively new (1,5yo) chat protocol with a small community.
This introduces support for Harmony into Matterbridge, using the functionality
specifically designed for bridge bots. The implementation is a modest 200 lines
of code.

### CODE REVIEW

**Comment by 42wim** [comment]
Thank you for the PR, could you fix the linter issue, just `gofumpt -w -s` the file.
Can you also extend the https://github.com/42wim/matterbridge/blob/master/matterbridge.toml.sample file with your bridge documentation ? (and if possible the wiki https://github.com/42wim/matterbridge/wiki too).

Is there a test harmony chat server available somewhere?

**Comment by pontaoski** [comment]
okay.

btw, can i ask what's up with the xmpp dependency? it's making developing on matterbridge near impossible since i need to surgically update the go.mod, go.sum, vendor/modules.txt, and vendored packages myself since the referenced commit isn't valid and only exists in the vendored copy matterbridge has.

**Comment by pontaoski** [comment]
added example to .sample

**Comment by 42wim** [comment]
> btw, can i ask what's up with the xmpp dependency? it's making developing on matterbridge near impossible since i need to surgically update the go.mod, go.sum, vendor/modules.txt, and vendored packages myself since the referenced commit isn't valid and only exists in the vendored copy matterbridge has.

That's fixed now with PR #1661 , you'll have to rebase for the `go.sum` though :/
(The `matterbridge` branch on the xmpp dependency was rebased and I forgot to update the go.mod)

**Comment by pontaoski** [comment]
> > btw, can i ask what's up with the xmpp dependency? it's making developing on matterbridge near impossible since i need to surgically update the go.mod, go.sum, vendor/modules.txt, and vendored packages myself since the referenced commit isn't valid and only exists in the vendored copy matterbridge has.
> 
> That's fixed now with PR #1661 , you'll have to rebase for the `go.sum` though :/ (The `matterbridge` branch on the xmpp dependency was rebased and I forgot to update the go.mod)

thanks! that'll make stuff much easier to hack on.

rebased the branch.

**Comment by 42wim** [comment]
🚀 thanks!

**Comment by pontaoski** [comment]
Thanks!

Added a wiki page for Harmony configuration now :)

**Comment by 42wim** [comment]
@pontaoski thanks, appreciated!

**Pull request merged**
