### PR TITLE
Matterbridge as a linux systemd service

### PR DESCRIPTION
**Pull request by realrolfje**
Add scripts to have matterbridge run as a systemd daemon in Linux.

### CODE REVIEW

**Comment by 42wim** [comment]
Hi, thanks for the PR!
It seems like a mix between a sysv initscript and systemd though?

**Comment by realrolfje** [comment]
Could be. I cobbled it together based on the mattermost init.d script, I'm no expert. We needed it because when a connection drops, de bridge seemed to stop working. I decided that having it as a service would be nice, so we can do an easy restart, while also having the benefit of automatic starting at boot.

If you have tips or pointers on how to improve the script I'd be happy to improve this pull request.

**Comment by 42wim** [comment]
An example for a true systemd service unit can be found here
https://github.com/42wim/matterbridge/issues/116#issuecomment-299642840

Normally you put those files in /etc/systemd/system 

The daemon-reload, enable and start commands remain the same.

**Comment by heinrich5991** [comment]
I have this:

``` 
[Unit]
Description=matterbridge
After=network.target

[Service]
ExecStart=/usr/bin/matterbridge -conf /etc/matterbridge/bridge.toml
User=matterbridge
Group=matterbridge

[Install]
WantedBy=multi-user.target
```

Should I make a pull request? It's helpful when projects have some standard service files. :)

**Comment by 42wim** [comment]
@heinrich5991 looks good, sure, go ahead :)

**Comment by patcon** [comment]
FYI, this is something related, which you might consider directing folks toward instead of including init scripts :)
https://github.com/jordansissel/pleaserun

**Comment by patcon** [comment]
So this would mean:

```
sudo mkdir -p /opt/matterbridge/bin
sudo cp matterbridge-$ARCH /opt/matterbridge/bin
gem install pleaserun
pleaserun --install  /opt/matterbridge/bin/matterbridge
```

Puts it in the users hands to install ruby, but then it works on any platform `pleaserun` supports :)

**Comment by 42wim** [comment]
@patcon feel free to edit stuff about this on the wiki, I'm going to close this PR now as @heinrich5991 #291 is merged.

**Pull request closed without merging**
