### PR TITLE
Add UserID to RemoteNickFormat and Tengo

### LINKED ISSUE #487: {USERNAME} placeholder in config
**Is your feature request related to a problem? Please describe.**
After upgrading to mattermost 5.2.1 and the latest matterbridge, we notice that the behavior of {NICK} in the config file is changed.  It used to display the username of the mattermost user, and now it displays the nickname of the mattermost user. This feels like a bugfix and correct, but we'd like to display the username of the mattermost user. 

**Describe the solution you'd like**
For that, I'd like to ask for a {USERNAME} placeholder in the config file so we can reinstate our original setup.

### PR DESCRIPTION
**Pull request by JeremyRand**
Fixes #487.  I used `{USERID}` instead of `{USERNAME}` for less ambiguity because the term "Username" is already used in Tengo to refer to the nickname.

### CODE REVIEW

**Comment by JeremyRand** [comment]
Not sure what to do about the `wrapperFunc` lint error; I just copied the style of the surrounding code.

**Comment by 42wim** [comment]
Thanks!

The linting tells you to use `ReplaceAll` instead of `Replace`, only new code gets linted (as there is too much old code that doesn't pass the linter). Could you change that?

I don't really see how it fixes #487 ? It's still a useful PR though.

**Comment by JeremyRand** [comment]
> The linting tells you to use `ReplaceAll` instead of `Replace`, only new code gets linted (as there is too much old code that doesn't pass the linter). Could you change that?

Okay, I'll do that; might take me a day or two to update the PR.

> I don't really see how it fixes #487 ? It's still a useful PR though.

Maybe I'm missing something -- that issue is about the RemoteNickFormat not being able to access the user ID, no?  I.e. if I have a Matrix user, RemoteNickFormat only can access the display name (e.g. `Jeremy_Rand`) as opposed to the user ID (e.g. `@Jeremy_Rand:matrix.org`).  That's what this PR fixes (the user ID can be accessed independently of the display name).  Am I misunderstanding what that issue is talking about?

**Comment by 42wim** [comment]
> Maybe I'm missing something -- that issue is about the RemoteNickFormat not being able to access the user ID, no? I.e. if I have a Matrix user, RemoteNickFormat only can access the display name (e.g. `Jeremy_Rand`) as opposed to the user ID (e.g. `@Jeremy_Rand:matrix.org`). That's what this PR fixes (the user ID can be accessed independently of the display name). Am I misunderstanding what that issue is talking about?

In mattermost the userid is a random ascii string like `wsq4jko6ctyfjybyxnuy6h114y`
I think matrix is one of the few that doesn't have a generated userid.

**Comment by JeremyRand** [comment]
> In mattermost the userid is a random ascii string like `wsq4jko6ctyfjybyxnuy6h114y`
> I think matrix is one of the few that doesn't have a generated userid.

Ah, interesting, I wasn't aware of this.  Should I edit the commit message to remove the reference to that issue, then?  (Matrix is all I need for my purposes, so I'll probably pass on trying to implement Mattermost support for this use case.)

**Comment by 42wim** [comment]
I removed the fix for mattermost and squashed your commits, thanks for this PR!

**Pull request merged**
