### PR TITLE
Discord: Split messages if necessary

### PR DESCRIPTION
**Pull request by BenWiederhake**
Old behavior: Telegram user sends a huge 4096-byte message (the maximum permitted by Telegram), it gets clipped to 1950 bytes on Discord.

New havior: Set `MessageSplitMaxCount=3` as config option of the Bridge, and it instead sends up to three messages to Discord (each of maximum length)

Note that this handles editing correctly, both in the "bot user" and "webhooks" cases.

This PR combines well with #2123.

I have no write permissions to the wiki, so I cannot add the appropriate documentation there.

### CODE REVIEW

**Comment by BenWiederhake** [comment]
Changes since last push: Refactored `Bdiscord.webhookSend` as suggested by the codeclimate bot.

**Comment by 42wim** [comment]
@BenWiederhake thanks for looking into this and adding tests 👍 
The wiki has set readonly because of spammers. I've invited you to the matterbridge/wiki on https://github.com/matterbridge/wiki/wiki if you want you can updated the wiki there (and will be synced to the wiki here also)

**Comment by BenWiederhake** [comment]
Awesome! It's good that you're back, I already got worried :)

**Comment by BenWiederhake** [comment]
Hmm, I can see neither of the wikis, and I don't see an invitation notification. :(

**Comment by BenWiederhake** [comment]
Done :)
https://github.com/matterbridge/wiki/wiki/Settings/_compare/7f12624afb1c79a6cab41b2c2839d11fe22d4c36...d554c45790bd3a713a4c0f2c9820338c2b5bb3ec

**Pull request merged**
