### PR TITLE
Enable !users command and add a table formatter

### PR DESCRIPTION
**Pull request by fdevibe**
* Listen to wildcarded events, currently handle RPL_NAMREPLY.
* Add a formatter to present nick lists from IRC as a table.

### CODE REVIEW

**Comment by 42wim** [comment]
Thanks for your work. I'd like to merge it, but I think the config fits better under [mattermost] instead of [irc]
(Also the case with your previous PR)

**Comment by fdevibe** [comment]
@42wim sure, if that's all, it should be quickly done. :smile:

**Comment by 42wim** [comment]
Ok, have been testing it now ;-) 
The header also shows NicksPerRow columns
image

Is prettier if that's not the case ;-)
image

**Comment by fdevibe** [comment]
Closed in favor of #14.

**Pull request closed without merging**
