### PR TITLE
Start documenting test scenarios

### PR DESCRIPTION
**Pull request by patcon**
I'm sure the deciding to use any specific tool should get more discussion, but just wanted to suggest that perhaps we could start keeping tracking of the scenarios that we know can create issues. Even if we never execute them, we can still use them to write future tests using another framework. Also, we can start asking people who encounter bugs to write scenarios for us, so that we can test later. This is a pretty low bar for participation. No everyone writes golang or tests, but everyone can look at the scenarios and make their own us :)

### CODE REVIEW

**Comment by patcon** [comment]
If we do feel like using BDD, this tool seems nicest: https://github.com/DATA-DOG/godog

Also, these exist:
- https://github.com/cucumber/gherkin-go
- https://github.com/gucumber/gucumber

**Comment by Helcaraxan** [comment]
Instead of writing scenarios that we then, somehow, somewhere will need to translate into tests via a yet unknown and undesigned testing framework I would really suggest we rather focus first on writing unit-test as suggested in #576 as those should cover already most of the scenarios that you would end up writing.

**Comment by patcon** [comment]
I respectfully, and wholeheartedly disagree. Not everyone who comes to these issue queues will be able to write tests. Not because they're lazy, but because they're not that sort of user. More places to hook people in makes for stronger community-building. This is perfect low-hanging fruit to engage drive-by users.

And personally, I've spent a many hours learning to write my few meager tests. Maybe you can do it more quickly, but sometimes I need to just jot down a new edge-case

Commons-based peer production (the academic word for what open source is) flourishes by creating as many niches for participation as possible. Documentation (incl hard-earned test scenarios) are part of that.

**Comment by Helcaraxan** [comment]
I think I might not have expressed my opinion in the right way so apologies for that @patcon. I actually wholeheartedly agree with your point-of-view on encouraging and building contributions. No discussion there.

The point I was trying to convey was that the usefulness of the resulting scenarios would be very meagre without an actual way / enactable way of putting them to good use. This means that my argument is technical in nature and has nothing to do with either contribution building or the varying degree of knowledge of potential contributors.

I have already given quite some thought to the possibilities of enabling easier & meaningful testing so that other people can contribute. Just like you would like to see as well! However this thinking has not yet been fruitful as all my existing ideas up to now have walked into technical difficulties or other similar roadblocks. That's not to say, on the contrary, that there is no good solution, just that I have not encountered it yet and that I am not _currently_ convinced by your approach either.

I would encourage thinking about this more before even trying to build / contribute anything. We can open up a relevant issue for it to contain the discussion. And I'll be more than happy to take part in it. If we can agree with you, @42wim and me on an approach after the necessary discussion and technical evaluation we can decide on how to move forward and what we need to do / build to facilitate those so much sought after contributions.

From my perspective I would not like, in any situation, to encourage people to contribute to something whilst also knowing that those contributions might very well not be of any use. I hope we can agree on that point at least.

**Comment by 42wim** [comment]
I agree with @Helcaraxan and especially this point:

> From my perspective I would not like, in any situation, to encourage people to contribute to something whilst also knowing that those contributions might very well not be of any use. I hope we can agree on that point at least.

Regarding to contribution, I'm not sure how we can encourage this more. 
People can already contribute in the wiki, it's as low-entry as can be and it doesn't happen that often.

**Comment by 42wim** [comment]
I don't think there is going to be any further work on this PR?
If so, please reopen, but closing for now.

**Pull request closed without merging**
