### PR TITLE
Show IRC colors when bridging to IRC

### PR DESCRIPTION
**Pull request by chotaire**
### Show IRC colors when bridging to other IRC channels

IRC colors were stripped when sending to another IRC channel.

- Removed generic IRC color stripping from IRC handlers
- Added IRC color stripping to all protocol bridges other than IRC

This should fix https://github.com/42wim/matterbridge/issues/798. I have only tested with IRC and Rocketchat, please review and optimize.

Thanks for your time.

### CODE REVIEW

**Comment by chotaire** [comment]
All checks now passed. Push rights to https://github.com/chotaire/matterbridge/tree/irc-enhancements granted to 42wim. Feel free to optimize my mess and make IRC users happy :)

**Comment by chotaire** [comment]
QA: I built a test binary which is available here: https://github.com/chotaire/matterbridge/releases/tag/v1.14.3-pre-irc-colors

**Comment by qaisjp** [comment]
This regex is being redefined and recompiled every message send — are you sure you don't want to just define it once in another package and then use it?

**Comment by chotaire** [comment]
Thank you for taking your time to review @quaisjp and you're right, that makes more sense. I'm new to Go. I'll work on a child package later this week. Have a good one! If you would like to commit something in the meantime, do not hesitate.

**Comment by chotaire** [comment]
Updated binary at https://github.com/chotaire/matterbridge/releases

**Comment by 42wim** [comment]
Hi @chotaire thanks for your work, much appreciated!

### About the IRC colors PR
I'm adding some code to refactor this issue using tengo, by removing the code from matterbridge and moving them into scripts. That way everyone can easily add/remove features they don't like.
So I'm putting this PR on hold for now, if my redesign doesn't work out, we can look at merging your PR.

### About the `Verbose IRC joins/parts`
Good idea to make this more verbose, but could you open a separate PR for this?
You also don't need to make an option for this, it's a debug message, it benefits from giving more information, so you can make a PR to make your changes the default.

**Comment by chotaire** [comment]
Hi wim, please look at the code for verbose IRC joins/parts. It's not only a debug message, it will be bridged over the relay.  Example:

VerboseJoinPart = true
`<system> Chotaire (chotaire@example.com) parts`

VerboseJoinPart = false
`<system> Chotaire parts`

I thereby believe it is good to make it an option. While IRC users would expect to see ident@host as a measure of identifying if someone is real, this information may not be wanted when bridging to other protocols, whether that be for privacy reasons or because they liked the previous behaviour. 

Thanks for taking your time to review.

**Comment by 42wim** [comment]
@chotaire oops, sorry.

Good arguments :)
Could you open a separate PR with this feature though? (looks good as-is)

**Comment by chotaire** [comment]
Moving" Verbose joins/parts" to separate PR.

This is the binary for testing "Show IRC colors when bridging to IRC": 
https://github.com/chotaire/matterbridge/releases/tag/v1.14.3-pre2-irc-colors

**Comment by chotaire** [comment]
Here is a merged binary with both https://github.com/42wim/matterbridge/pull/805 and https://github.com/42wim/matterbridge/pull/801:

♥ https://github.com/chotaire/matterbridge/releases/tag/v1.14.3-pre4

**Comment by poVoq** [comment]
Any news when this will be merged?

**Comment by chotaire** [comment]
> Any news when this will be merged?

It is no longer necessary to be merged. You can now use tengo to strip IRC colors only if you're not relaying to IRC. See https://github.com/42wim/matterbridge/pull/806

**Pull request closed without merging**
