### PR TITLE
Solved PR

### PR DESCRIPTION
**Pull request by thealidev**
https://github.com/42wim/matterbridge/pull/2068

New solver pr of it

### CODE REVIEW

**Comment by thealidev** [comment]
Screenshot_20230915-031613_Chrome

Look
How everything is mixed
All your dev chats
It gives me creeps

**Comment by thealidev** [comment]
@BenWiederhake
Here

**Comment by BenWiederhake** [comment]
Wow, yeah, that looks bad, you're right.

Inserting a bunch of random linebreaks is a terrible solution however.

**Comment by thealidev** [comment]
Then
Merge it

**Comment by thealidev** [comment]
Wait
Why is it closed

**Pull request closed without merging**
