### PR TITLE
Add vk bridge

### PR DESCRIPTION
**Pull request by ivanik7**
This PR adds support for chat bridging to [VK](https://vk.com/).

210125-104214-Мессенджер_-_Google_Chrome-chrome

# What works

- Forwarding text messages
- Forwarding images, voice messages, stickers and documents
- Edit messages in Vk

# What does not works

- Video upload via bots API limitation
- Video download (just URL in message now, maybe workaround in future)
- Edit and delete message in VK via API limitation
- Music via API limitation 

# Config example
```toml
[vk.myvk]
#Group access token
#See https://vk.com/dev/bots_docs?f=1.1.%20%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BA%D0%BB%D1%8E%D1%87%D0%B0%20%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%B0
Token="Yourtokenhere"

#Group ID
#For example in URL https://vk.com/public168963511 group ID is 168963511
GroupID=123456789

#If enabled this will relay attachments as URLs
UseFileURL=false

[[gateway.inout]]
account="vk.myvk"
#A number that starts form 2000000000. Use --debug and send any message in chat to get PeerID in the logs 
channel="2000000002"
```

# Token obtaining

Create group then `Manage > API Usage > Create Token`
image
Then enable longpoll at version 5.126 and enable `Message recived` event
image
image

### CODE REVIEW

**Comment by 42wim** [comment]
@ivanik7 looking good! 💯 
Is it ready for review or are you still working on it?

Are you also willing to add some docu in the wiki?  (analogue to the other protocols)

- https://github.com/42wim/matterbridge/wiki/Section-VK-%28basic%29
- https://github.com/42wim/matterbridge/wiki/Gateway-config-%28channel-rules%29

**Comment by ivanik7** [comment]
I think it's ready. This bridge has already working fine for about two days in chat.

**Comment by 42wim** [comment]
The only part I'm having some questions about is the `UseFileURL` option.

Are links to attachments on vk.com public? So if someone pastes an image on vk.com and the bridge relays it to irc for example, can that use click on that link and view it even if he doesn't have an account on vk.com ?

**Comment by ivanik7** [comment]
Yes, links in VK are publiс

[Link example](https://sun9-8.userapi.com/impf/p5FsWVv3RrfbV6tACkyHm7-3_QY7CAc2E_qkXg/r_4B4Xe8Etw.jpg?size=799x285&quality=96&proxy=1&sign=8413b5d52826cd7203d256b25e809ffc&type=album)

**Comment by 42wim** [comment]
Ok, I don't think we need the `UseFileURL` option.

The matterbridge "design" is if a bridge supports native uploading of content (like discord), the native upload should be used. If it doesn't support this (like irc), the URL should be used for public content (or the mediaserver for private content, which isn't the case here)

What is the need for the `UseFileURL` option?

**Comment by ivanik7** [comment]
It seems I misunderstood how to handle files)

**Comment by 42wim** [comment]
🚀 Thank you, great work!

**Pull request merged**
