### PR TITLE
img: Add updated screenshots for Slack-setup wiki.

### PR DESCRIPTION
**Pull request by chrisbobbe**
In particular, for this page:
  https://github.com/42wim/matterbridge/wiki/Slack-bot-setup#bot-based-setup.

It doesn't look like it's possible to upload images directly in the
edit-page UI, so I'm adding them with a PR. I plan to edit the
wiki's instructions and replace the outdated screenshots with these,
and then send another PR to delete the outdated screenshots from the
img directory.

### CODE REVIEW

**Comment by qaisjp** [comment]
These images can be uploaded to GitHub's servers, without needing to store it in-repo, by pasting into an issue comment — and you can use that URL anywhere!


https://user-images.githubusercontent.com/923242/119396476-ca668a00-bccc-11eb-9d66-3e11d74ea154.mov

**Comment by chrisbobbe** [comment]
Thank you, I'll use that approach!!

**Comment by qaisjp** [comment]
Thank _you_ for updating the docs :) ✨

**Comment by chrisbobbe** [comment]
> These images can be uploaded to GitHub's servers, without needing to store it in-repo, by pasting into an issue comment — and you can use that URL anywhere!

Here are the images, for me to get those links:

slack-setup-add-scopes1

slack-setup-app-page1

slack-setup-copy-token

slack-setup-create-app1

slack-setup-create-bot1

slack-setup-install-confirm

slack-setup-install-to-workspace

slack-setup-oauth-and-permissions

slack-setup-with-scopes-added

([click to scroll to the message above this one, it's long](https://github.com/42wim/matterbridge/pull/1490#issuecomment-847277117))

**Comment by chrisbobbe** [comment]
Done; I've updated the Slack setup instructions: https://github.com/42wim/matterbridge/wiki/Slack-bot-setup#bot-based-setup. They've worked for me; please ping me if people report that they're not working.

**Comment by qaisjp** [comment]
Cool! Works great here.

(Btw, it's fine that you submitted the images in the comment above, but in case you don't know, you don't actually have to submit the comment for the URLs to be valid and usable! Who knows, maybe 5 years from now GitHub will garbage collect the links.)

**Comment by chrisbobbe** [comment]
> Works great here.

Great! Glad to hear it. 😄 

> (Btw, it's fine that you submitted the images in the comment above, but in case you don't know, you don't actually have to submit the comment for the URLs to be valid and usable! Who knows, maybe 5 years from now GitHub will garbage collect the links.)

Yeah, I thought about not submitting the images in the comment. But then I could imagine a garbage-collection plan where GitHub deletes images that don't appear in a comment somewhere, while keeping images that do. So I figured I might as well keep them in the comment. 🤷

**Comment by 42wim** [comment]
@chrisbobbe thanks for your work, greatly appreciated! 👍

**Pull request closed without merging**
