### PR TITLE
Update vendor yaegashi/msgraph.go to v0.1.2

### PR DESCRIPTION
**Pull request by qaisjp**
They fixed the macOS bug I was having - https://github.com/yaegashi/msgraph.go/issues/11

### CODE REVIEW

**Comment by 42wim** [comment]
Did you rebase / tested the changes in my fork?

**Comment by qaisjp** [comment]
matterbridge binary builds, but I haven't _tested_ ms teams.

The only content commit in your fork is https://github.com/matterbridge/msgraph.go/commit/ce5df2f44e100e89f531d729fbbb7e6a8e9f9b1a and I can confirm that the enums are corrected in the v0.1.2

```bash
➜ ag "type BodyType"
vendor/github.com/yaegashi/msgraph.go/beta/EnumBody.go
6:type BodyType string

➜ ag "type ChatMessageImportance"
vendor/github.com/yaegashi/msgraph.go/beta/EnumChat.go
6:type ChatMessageImportance string

➜ ag "type ChatMessageType"
vendor/github.com/yaegashi/msgraph.go/beta/EnumChat.go
124:type ChatMessageType string
```

So I've switched it over from your fork to the upstream repo.

**Comment by qaisjp** [comment]
(The enum types were fixed in https://github.com/yaegashi/msgraph.go/pull/6 upstream)

**Comment by 42wim** [comment]
Ok, I'll test this if I can find some time.
Was planning on releasing v1.17.0 soon with the ms teams support. 
It's possible that this PR will be merged after v1.17.0 depending on my time :)

**Comment by qaisjp** [comment]
Okay!

**Comment by 42wim** [comment]
Thanks! tested and working

**Pull request merged**
