### PR TITLE
nctalk: append a suffix if user is a guest user

### PR DESCRIPTION
**Pull request by gary-kim**
Signed-off-by: Gary Kim <gary@garykim.dev>

### CODE REVIEW

**Comment by 42wim** [comment]
I'm wondering if this shouldn't be configurable by users, eg that they can choose what to add.
eg `GuestSuffix="(Guest)"` or `GuestString` or something like that :-)

**Comment by gary-kim** [comment]
I like that idea, gimme a bit

**Comment by s3lph** [comment]
While you're at it, would it be possible to add a config option to show the user ID instead of the display name for non-guest users? Use case: The affected Nextcloud gets its user accounts from an LDAP directory with nicknames as UIDs and full names as display names. However, in channels which are bridged to public IRC, I'd prefer to use nicknames rather than full names.

I'd open a pull request myself, but since you're already working on something similar, I thought I'd ask first.

**Comment by gary-kim** [comment]
@s3lph 
I can see how that would be useful. I'd rather not include it into this PR though so I'll get to it after this PR. Feel free to work on it yourself if you'd like, though.

**Comment by 42wim** [comment]
:+1:

**Pull request merged**
