### PR TITLE
Telegram topics

### PR DESCRIPTION
**Pull request by cosmicboots**
This is a ~~work in progress~~ PR to support the topics feature found in telegram supergroups.

The `telegram-bot-api` library update is keeping this as a work in progress for now. When the new API changes are merged into the library (https://github.com/go-telegram-bot-api/telegram-bot-api/pull/621), this PR can be updated and moved out of draft status.

Topics are surfaced by appending `/<topic-id>` to the `channel` setting for the gateway. An example for the topic with ID of 16 would be:
```toml
[[gateway.inout]]
account="telegram.mytelegram"
channel="-100xxxxxxxxxx/16"
```

This should fix issue #1916

### CODE REVIEW

**Comment by GEkuL** [comment]
pls, change the link in head to https://github.com/go-telegram-bot-api/telegram-bot-api/pull/633 , since the API is updated to 6.5 version

**Comment by oizyumov** [comment]
@cosmicboots hi there, so can I somehow use the per-topic connection already?
Setting up a gateway like you've described in the header?

Or somehow build a version supporting the functionality (with the pre-built version of the corresponding library with the merged issue)?

**Comment by cosmicboots** [comment]
@oizyumov you should be able to use this branch if you tell go to use the updated fork of `go-telegram-bot-api`.

I had this in my `go.mod` when i was testing:
```
replace github.com/go-telegram-bot-api/telegram-bot-api/v5 => github.com/OvyFlash/telegram-bot-api/v5 v5.0.0-20221231001529-5e115c98c785
```

**Comment by oizyumov** [comment]
In case somebody as me is interested in the realization of topics ASAP, 

Here's how you can do that via Docker:
0) clone cosmicboots repo via `git clone git@github.com:cosmicboots/matterbridge.git` and switch to the "telegram-topics" branch

1) instead of alpine container in Dockerfile for builder, use "golang:1.19.6-alpine3.17",  which requires more space, however provides easier options to rebuild the container

2) remove `go` package from Dockerfile (since we've already specified the go version for builder)

3) clone OvyFlash repo `git clone git@github.com:OvyFlash/telegram-bot-api.git`

4) switch to the latest branch of its (OvyFlash repo) PR to go-telegram-bot-api to support topics:
`git branch -v -a` provides the list of branches
`git switch <branch name>` pick the latest version branch

5) go to the `matterbridge/vendor/github.com/go-telegram-bot-api` folder and check the content of telegram-bot-api folder

6) replace the containing telegram-bot-api folder with (or rename to .backup and copy inplace) the cloned repo with the active branch.
Inside the telegram-bot-api folder create a v5 folder copying the needed files there, so it's similar to the structure of the original telegram-bot-api

7) use `sudo docker build -t "matterbridge:topics" .` to create the image of the matterbridge image supporting topics

**Comment by 42wim** [comment]
@cosmicboots I've forked telegram-bot-api on https://github.com/matterbridge/telegram-bot-api and added the latest patch from https://github.com/go-telegram-bot-api/telegram-bot-api/pull/633

You can use this fork in this PR as `github.com/matterbridge/telegram-bot-api/v6`

We'll use upstream again when the PR gets merged there.

**Comment by cosmicboots** [comment]
@42wim I've updated the PR to use the updated fork you provided. Please let me know if you need anything else from me.

**Comment by glasgowm148** [comment]
Doesn't work

**Comment by GEkuL** [comment]
@glasgowm148 provide your config file

**Pull request merged**
