### PR TITLE
Allow captions for document attachments, too

### PR DESCRIPTION
**Pull request by ilmaisin**
This seems to be sufficient to fix https://github.com/42wim/matterbridge/issues/1925

### CODE REVIEW

**Comment by ilmaisin** [comment]
Closed the old one and opened another, because the previous one used the base branch of my fork instead of a dedicated branch

**Comment by ilmaisin** [comment]
I'll need to take a look at this. [The documentation](https://developers.facebook.com/docs/whatsapp/on-premises/reference/media) says this does not work, though I saw it working...

**Comment by ilmaisin** [comment]
https://developers.facebook.com/docs/whatsapp/api/messages/media/ This on the other hand says that you can have a document caption as a sepatate thing from filename...

**Comment by ilmaisin** [comment]
https://www.timesnownews.com/technology-science/whatsapp-rolls-out-document-caption-feature-to-some-beta-users-article-94692173 The document caption feature was only recently added to WA.

**Comment by 42wim** [comment]
going to close this in favor of #1928

**Pull request closed without merging**
