### PR TITLE
Implement Rocket.Chat attachments handling

### PR DESCRIPTION
**Pull request by drndos**
I have implemented working version of rocket.chat attachments and tested it with Rocket.chat -> Slack.
TODO: 
- [ ] Generify DownloadFileAuth
- [ ] Remove unnecessary dependencies from handlers
- [x] do we actually need "rocket_attachments"?
- [x] More caching options ?
- [x] More checks if file is ok ?
- [ ] Even more checks if file is ok and better handling if not
- [x] Actually use cache ? is it even  necessary ?
- [ ] Think more about texts of attachment

If anyone has any worthy opinion please share, thanks.

### CODE REVIEW

**Comment by 42wim** [comment]
Thanks for contributing 👍 
If you need any help feel free to ask here or on the [chat](https://github.com/42wim/matterbridge/#chat-with-us)

### Some answers on your questions:
> do we actually need "rocket_attachments"?

Too bad it's incompatible with slack attachments.. mattermost/slack use the same structure.
So I'm afraid we'll need to have a separate until a better idea pops up. Maybe call it "rocketchat_attachments" (it's longer, but more consistent with the naming)

> More checks if file is ok ?

I think you're referring to that check in the slack code ? That's because the slack servers are too slow (or matterbridge too fast) in downloading the file, the URL is already there, but the file wasn't on the server yet. I'm not sure if that's the case with rocketchat, so maybe you can drop that check.

> Actually use cache ? is it even necessary ?

With slack the cache is there because of the way slack announces file events, iirc it does it multiple times, so too avoid downloading the same file also multiple times the cache is there. If rocketchat does it only once, you could drop the cache.

### Travis/build errors
Before we can merge this, the errors on [travis](https://travis-ci.org/42wim/matterbridge/builds/501765450?utm_source=github_status&utm_medium=notification) should be fixed. 
Don't hesitate to ask questions if it isn't clear on how to fix this.

**Comment by drndos** [comment]
more TODO:
* What to do when rocket.chat restarts, it seems that the matterbridge needs restart after that
* When sending ZIP files over the bridge it seems that either some HTML page is sent or the bridge hangs and fails
* Also it would be great if we could resend all the messages that didn't get relayed after hang

**Comment by drndos** [comment]
Testing it on production like a boss :). I found some bugs and will need to implement some kind of monitoring because the process doesn't get killed but the messages are not getting relayed in some conditions.

**Comment by 42wim** [comment]
I've noticed the "What to do when rocket.chat restarts, it seems that the matterbridge needs restart after that" issue myself, and am running a patch on my own bot. https://github.com/42wim/matterbridge/commit/1539185bd47dba573c7bf7c6de2470336940bdf4

Not sure if you're seeing the same messages about invalid and expired login or if you have another issue.

**Comment by 42wim** [comment]
Let me know if you need any help. :)

**Comment by 42wim** [comment]
implemented in another PR

**Pull request closed without merging**
