### PR TITLE
Solve Readme Mixing Error In Mobiles

### PR DESCRIPTION
**Pull request by thealidev**
You can check yourself
What i have solved 😀

### CODE REVIEW

**Comment by thealidev** [comment]
https://github.com/42wim/matterbridge/pull/2068.patch

**Comment by thealidev** [comment]
I don't think so it is longer maintained
Why don't i am getting a reply

**Comment by BenWiederhake** [comment]
Two of your commits cancel each other out (the first and third). Please remove.

The second commit adds bad newlines, please fix that. This leaves an empty commit, please remove.

What is the point of this PR?

**Review by thealidev — COMMENTED** [review]
Solved

**Comment by thealidev** [comment]
Wait a minute
I will open another pr

**Comment by thealidev** [comment]
Screenshot_20230915-031613_Chrome

This was purpose of pr btw

**Pull request closed without merging**
