### PR TITLE
Telegram: add markdown

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
Telegram has the non-standard "markdown" style. This ugly replacement logic is hard to understand but works properly. Tested.

### CODE REVIEW

**Comment by 42wim** [comment]
Thanks, but I think this should be fixed by regexp, so we are more certain we're not changing random * or _ in sentences ?

**Comment by ishitatsuyuki** [comment]
Oh. Good point, will find another method with regexp.

**Comment by ishitatsuyuki** [comment]
I'm very lazy, so I decided to use a mature parser. This works perfectly, with many syntax extensions ported.

**Comment by 42wim** [comment]
Thanks for the work, I've got one question though, why not using the default BlockCode and Paragraph ?

**Comment by ishitatsuyuki** [comment]
I'm blacklisting the tags that Telegram doesn't parse. `<p>` and `<code>` will cause an error resulting in the message not delivered.

**Comment by ishitatsuyuki** [comment]
Please wait for an update to also blacklist "quote".

> this is a quote

**Comment by 42wim** [comment]
Thanks!

**Pull request merged**
