### PR TITLE
Matrix: switch to the mautrix-go library

### PR DESCRIPTION
**Pull request by nightmared**
Replaces https://github.com/matrix-org/gomatrix with https://github.com/tulir/mautrix-go as it appear to be the successor (see https://github.com/42wim/matterbridge/issues/1187#issuecomment-688986854).

This could be a stepping stone for #137 and #1187.

Note that for reducing rebases this currently depends of #1541, however I will happily change that if #1541 is rejected.

Hopefully one day we will have encryption support with appservices for matrix ;)

### CODE REVIEW

**Comment by nightmared** [comment]
FYI I'm currently looking at adding a very basic appservice support for matterbridge using this patch, you can see what it looks like at https://github.com/nightmared/matterbridge/tree/mautrix_appservice.

**Comment by TheHolyRoger** [comment]
@nightmared you bloody beast thank you! I can help review and test this, I did briefly try to tackle it before.

Does this support encryption already?

**Comment by nightmared** [comment]
I haven't yet tried it against encrypted room, there is probably more work to be done to support it (like some mechanism to store keys across sessions maybe ? I have to admit I don't know much of the way keys are managed in the matrix world, I would have to take a look. Do you know about it maybe ?)

**Comment by 42wim** [comment]
Hi @nightmared thanks for your work! I'll try to review it this week

**Comment by poVoq** [comment]
Would be great to have this merged *sorry for nagging*

**Comment by nightmared** [comment]
I think I'm going to work on https://github.com/42wim/matterbridge/pull/1544 on the next few evenings (that draft PR depends on this PR), which will offer me the occasion to test this a bit further.
In any case, if you have tested this and it worked (and even more if it didn't), please share ;)

**Comment by w3bb** [comment]
> I haven't yet tried it against encrypted room, there is probably more work to be done to support it (like some mechanism to store keys across sessions maybe ? I have to admit I don't know much of the way keys are managed in the matrix world, I would have to take a look. Do you know about it maybe ?)

A lot of bots just use [Pantalaimon](https://github.com/matrix-org/pantalaimon/).

**Comment by nightmared** [comment]
I'm not currently working on this, so I'm gonna close this for now.

**Pull request closed without merging**
