### PR TITLE
Update discord.go

### PR DESCRIPTION
**Pull request by greenlighttec**
Added bolding around the name, and split the name vs message with ": " on line 338

### CODE REVIEW

**Comment by 42wim** [comment]
You should use `RemoteNickFormat` config for changing the nick appearance.

**Comment by greenlighttec** [comment]
I mean I'll look at that, but the current code is purposely stringing the name and message together without any kind of separation. Surely that cannot be intended design?

**Comment by greenlighttec** [comment]
Ok the `RemoteNickFormat` changes the display for ALL messages. I'm specifically fixing an issue in threads (with `PreserveThreading` set to true) that the name of the person sending the message (Since the sender is the bot name) and the message itself is concatenated together and looks dumb. My changes will fix this and make the threads easier to read. 

image

You can see the Bot messages look fine, but the thread reply looks ridiculous.

**Comment by greenlighttec** [comment]
Okay, I compiled the changes I suggested and tested and found that they didn't actually do anything lol. Definitely not what I was trying to achieve. I spent some more time actually reading through the code and I think i'm in the wrong place to influence the messages being sent when a thread is occurring. You can ignore this for now if I find out where to do the change I'll make a new pull request.

**Comment by jonaswouters** [comment]
Did you ever solve this @greenlighttec because I think this was a clean solution

**Comment by greenlighttec** [comment]
https://github.com/mspgeek-community/matterbridge

**Pull request closed without merging**
