### PR TITLE
Add Docker Compose configuration

### PR DESCRIPTION
**Pull request by pbek**
I like the project and use it with Docker Compose, this would be the configuration for all who use Docker Compose too.

### CODE REVIEW

**Comment by qaisjp** [comment]
Is it normal to use Docker Compose instead of plain Docker for single-service applications?

**Comment by pbek** [comment]
If you are running your other containers also via docker compose it makes sens.

**Comment by 42wim** [comment]
@pbek thanks!

I think this would fit better in the wiki.

Would you like to make a page like this https://github.com/42wim/matterbridge/wiki/Deploy:-Azure but for docker (eg https://github.com/42wim/matterbridge/wiki/Deploy:-docker) and put the docker and your docker-compose example in it?

And then just add a link from the README to the wiki.

**Comment by pbek** [comment]
Done.

**Comment by 42wim** [comment]
Thank you! 👍

**Pull request merged**
