### PR TITLE
rudamentary support for signald

### PR DESCRIPTION
**Pull request by petermolnar**
Signald https://gitlab.com/signald/signald is a standalone Signal client written in Java that can be interacted with via Unix socket and newline separated JSON strings.

These commits establish a crude and basic interaction with the signald daemon where by giving a group ID, one can relay messages from and to a Signal group.

Anything beyond this functionality - including, but not limited to registration, device linking, joining a group, etc. - is missing.

To test the functionality one has to set up signald with linking or registration in advance.

### CODE REVIEW

**Comment by 42wim** [comment]
@petermolnar thank you!
Could you fix the linting errors? If anything is not clear, let me know

**Review by halms — CHANGES_REQUESTED** [review]
First: I very much look forward to this getting merged. I have a specific use case where bridging a WhatsApp with a Signal group is really useful.

It seems your latest changes fixed the linting errors.

When trying this out though, I run into some very weird behavior (my Signal groups got mixed up, ...) and I think I tracked it with the suggested changes.

Let me know, what you think (this is my first time touching Go code...).

**Comment by halms** [comment]
Is there any update on the status of this PR?
It seems to need a rebase now.

I have a version of this (with my described changes) running since a month or so on a local instance and have not run into any big issues.

**Comment by micw** [comment]
@42wim What changes (besides a rebase) are required to bring this in a state that you'd merge?
Kind regards,
Michael.

**Comment by 42wim** [comment]
@petermolnar looks like @halms suggestions are useful, are you willing to rebase with his proposed changes?

To merge this I need someone who wants to take ownership of this specific bridge as I don't use signal/can't test it.

**Comment by 42wim** [comment]
@halms sounds good, thanks!

**Comment by z8512** [comment]
@halms waiting

**Comment by rihaq** [comment]
@halms https://github.com/42wim/matterbridge#building-with-whatsapp-beta-multidevice-support

**Pull request closed without merging**
