### PR TITLE
Fix Docker TGS to PNG

### PR DESCRIPTION
**Pull request by computeronix**
when attempting to convert TGS to PNG it errors, the below  PR fixes it

resolves: https://github.com/42wim/matterbridge/issues/1515

### CODE REVIEW

**Comment by 42wim** [comment]
There's a special dockerfile for this https://github.com/42wim/matterbridge/blob/master/tgs.Dockerfile

**Comment by computeronix** [comment]
Is this linked to  Docker Hub? if so which repro/tag is it in so i can pull it as is and test?
https://hub.docker.com/r/42wim/

**Comment by 42wim** [comment]
It is not linked to dockerhub, you need to build it yourself.

**Comment by computeronix** [comment]
thanks closing this PR and evaluating the file

**Pull request closed without merging**
