### PR TITLE
Add a ping keepalive endpoint to API

### PR DESCRIPTION
**Pull request by patcon**
~~Depends on this: https://github.com/42wim/matterbridge/pull/551~~

Also, will be used for https://github.com/42wim/matterbridge/pull/525 in keeping the service from sleeping on Heroku

### CODE REVIEW

**Comment by patcon** [comment]
Sorry, it was a little subtle, but I said that this depends on #551

**Comment by patcon** [comment]
Ok, I've just rebased it, since I feel like the other PR might take some discussion :)

**Comment by patcon** [comment]
:)

> If you're polling `/api/messages` or streaming `/api/stream` it shouldn't sleep

I don't expect to be polling them at all -- [as per your great suggestion](https://github.com/42wim/matterbridge/pull/525#issuecomment-434858085), I'm only using the API to kick off config reloads, but I don't plan to use it for messaging :)

> Wondering if it's not better to send a ping message to `/api/message`...

How were you thinking this might work? Like a special payload where a plaintext `pong` response comes back instead of a json response? Or using GET instead of POST?

> that's how slack/mattermost do it (with websockets on one endpoint though)

tbh I don't feel we should model on a websocket api, since RESTful API's aspire for semantic endpoints with homogenous resource objects returned (returning a consistent object per VERB), and websockets APIs don't necessarily abide by that (if I'm understanding correctly)

I'm inclined to vouch for having a ping endpoint, unless you feel strongly :)

**Comment by patcon** [comment]
Not that this was my intention, but now that I'm thinking about it, some sort of ping endpoint is a good candidate for [turning into a healthcheck endpoint](https://blog.runscope.com/posts/build-a-health-check-api-for-services-underneath-your-api). I feel it conceptually makes sense to not conflate the message reading/writing endpoint with the utility purpose of a keepalive/healthcheck

**Comment by 42wim** [comment]
Agree for a healthcheck handler, rename it to `/health` and let it return `OK` instead `pong` for now.

Websockets can do whatever you want :-) mattermost for example streams all their stuff over websockets, and uses ping as a keepalive over the websocket.

**Comment by patcon** [comment]
Done and done!

**Pull request merged**
